# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김하늘
title: Junior Backend Developer
email: aksmf1442@gmail.com
# email_title: Email (Email title override)
phone: 010-4733-1720
# phone_title: Phone (Phone title override)
website: https://haneuls-blog.super.site/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  aksmf1442

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/pro.jpg
about_content: | # this will include new lines to allow paragraphs
  - 운영 자동화, 모니터링 통합, 인프라 전환 등 실무 중심의 성과를 보유한 백엔드 개발자입니다.
  - <mark>빠른 학습력과 문제 해결 중심 사고</mark>로 다양한 실서비스 환경에서 기술적 개선을 주도해왔습니다.
  - DevOps와 백엔드 개발의 경계를 넘나들며 <mark>생산성과 안정성 모두에 기여</mark>할 수 있습니다.
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: H2o Korea
        sub_title: Backend Developer
        caption: 2023.06 ~ 재직중
        link: https://www.h2ohospitality.io
        quote: >
          호텔 산업 DX 솔루션 개발회사
        description: | # this will include new lines to allow paragraphs
          - 모니터링 서비스 구축 및 통합 경험
          - 인프라 구축 및 운영 관리
          - DB 성능 튜닝 및 장애 대응
          - 데이터베이스 마이그레이션 도구를 도입하여 팀 내 스키마 관리 및 배포 프로세스를 개선
          - 배포 프로세스 자동화로 팀의 업무 생산성 개선
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        quote: >
          <mark>H2O KOREA</mark>
      - layout: top-left
        title: S-REGI 서비스
        description: |
         - 호텔 체크인 전 사용자 정보 수집 및 약관 동의용 백엔드 개발
         - WebSocket 기반 실시간 통신 설계
         - JWT 인증·권한 관리
      - layout: top-left
        title: 호텔 통합 관리 서비스
        description: |
         - 호텔별 상이한 체크인 절차를 유연하게 처리할 수 있도록 모듈 설계 및 확장
         - 컨시어지, 룸클리닝, 스마트체크인, CRM 등 신규 서비스 초기 개발
         - 메시지 발송 시 ActiveMQ 기반 <mark>이벤트 발송 구조 설계 및 개발</mark>
      - layout: top-left
        title: Docker-Compose -> K8S 클러스터 전환
        description: | # this will include new lines to allow paragraphs
          - Docker-Compose 기반 설계에서 K8S 클러스터로 마이그레이션
          - 서비스 무중단 배포, 컨테이너 자동 복구, 롤백 등 오케스트레이션 구조 설계 및 운영
      - layout: top-left
        title: 모니터링 시스템 통합 (LGTM 스택 도입)
        description: | # this will include new lines to allow paragraphs
          - 기존 파일 로그 + ELK 혼재 환경을 LGTM(Grafana, Loki, Tempo, Prometheus)으로 전환
          - DB/Redis exporter, 서비스 로그, 분산 트레이싱 등 다양한 메트릭을 단일 대시보드에 통합
          - CPU/디스크/에러코드 기반 이메일 알림 시스템 구축으로 <mark>대응 시간 30% 단축</mark>
      - layout: top-left
        title: 데이터베이스 운영 효율화
        description: |
         - 마이그레이션 도구 [Flyway 도입](https://haneuls-blog.super.site/%ea%b0%9c%eb%b0%9c-%ec%a1%b0%ec%a7%81%ec%97%90-flyway%eb%a5%bc-%ec%99%9c-%eb%8f%84%ec%9e%85%ed%95%98%ea%b2%8c-%eb%90%98%ec%97%88%ec%9d%84%ea%b9%8c), 수동 쿼리 배포 방식 → 자동화된 스키마 관리 체계로 개선
         - Master-Slave 간 replication [delay 이슈 분석 및 구조 개선](https://haneuls-blog.super.site/db-masterslave-%ea%b0%84-%eb%8f%99%ea%b8%b0%ed%99%94-%ec%a7%80%ec%97%b0-%ec%9d%b4%ec%8a%88)
         - [느린 쿼리 Fetch Time 병목 분석 및 성능 개선 진행](https://haneuls-blog.super.site/base64%eb%a5%bc-%ec%bb%ac%eb%9f%bc%ec%97%90-%eb%84%a3%ec%9c%bc%eb%a9%b4-%eb%b2%8c%ec%96%b4%ec%a7%80%eb%8a%94-%ec%9d%bc%eb%93%a4)
      - layout: top-left
        title: 기타 DevOps 업무
        description: |
         - 폐쇄망 내 Nexus 프라이빗 이미지 레지스트리 연동 및 배포 자동화 구축
         - 사내 보안 강화를 위해 [VPN 서버 구성](https://haneuls-blog.super.site/note/%ed%9a%8c%ec%82%ac%ea%b0%80-vpn%ec%9d%84-%ec%83%88%eb%a1%9c-%ea%b5%ac%ec%b6%95%ed%95%98%ea%b2%8c-%eb%90%9c-%ec%9d%b4%ec%9c%a0-feat-%ec%84%9c%ec%9a%b8%eb%b3%b4%ec%a6%9d) 및 OPNsense 방화벽 설치 및 정책 설정
         - Jenkins 기반 파이프라인 구성 및 CI/CD 운영 최적화
  - title: Blog Posts
    layout: list
    content:
    - layout: left
      title: Backend
      description: | # this will include new lines to allow paragraphs
        [운영 효율성 강화를 위해 DB 마이그레이션 도구 도입 및 스키마 관리 자동화 체계 구축](https://www.notion.so/Flyway-2283d7c5e50c81b59d93f4350dcf6359)
  - title: Skill
    layout: list
    content:
    - layout: left
      title: Backend
      description: | # this will include new lines to allow paragraphs
        * Java
        * Spring Boot, Spring MVC, Spring Batch
        * JPA, Querydsl
        * Junit4/5, Mockito
        * Gradle
    - layout: left
      title: DevOps
      description: | # this will include new lines to allow paragraphs
        * MySQL, MariaDB
        * Jenkins
        * AWS EKS, S3, EC2, Route53
        * DockerSwarm, K8S
        * Nginx
        * Grafana, Prometheus, Loki, Tempo
        * Ubuntu
  - title: Education
    layout: list
    content:
      - layout: left
        title: 동의대학교
        sub_title: e-비즈니스학과
        caption: 2015.03~2022.02

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
