# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김하늘
title: Junior Backend Developer
email: aksmf1442@gmail.com
# email_title: Email (Email title override)
phone: 010-4733-1720
# phone_title: Phone (Phone title override)
website: https://haneuls-blog.super.site/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  aksmf1442

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  운영 자동화, 모니터링 통합, 인프라 전환 등 실무 중심의 성과를 보유한 백엔드 개발자입니다.
  빠른 학습력과 문제 해결 중심 사고로 다양한 실서비스 환경에서 기술적 개선을 주도해왔습니다.
  DevOps와 백엔드 개발의 경계를 넘나들며 생산성과 안정성 모두에 기여할 수 있습니다.
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: H2o Korea
        sub_title: Backend Developer
        caption: 2023.06 ~ 재직중
        link: https://www.h2ohospitality.io
        quote: >
          호텔 산업 DX 솔루션 개발회사
        description: | # this will include new lines to allow paragraphs
          - 모니터링 서비스 구축 및 통합 경험
          - 인프라 구축 및 운영 관리
          - DB 성능 튜닝 및 장애 대응
          - 데이터베이스 마이그레이션 도구를 도입하여 팀 내 스키마 관리 및 배포 프로세스를 개선
          - 배포 프로세스 자동화로 팀의 업무 생산성 개선
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Docker Compose 기반 단일 서버 환경을 Docker Swarm 기반 이중 서버 클러스터로 마이그레이션
        quote: >
          H2o Korea
        description: | # this will include new lines to allow paragraphs
          - 단일 서버 → K8S 클러스터 전환
          - 서비스 무중단 배포, 컨테이너 자동 복구, 롤백 등 오케스트레이션 구조 설계 및 운영
      - layout: left
        title: 모니터링 시스템 통합 (LGTM 스택 도입)
        description: | # this will include new lines to allow paragraphs
          - 기존 파일 로그 + ELK 혼재 환경을 LGTM(Grafana, Loki, Tempo, Prometheus)으로 전환
          - DB/Redis exporter, 서비스 로그, 분산 트레이싱 등 다양한 메트릭을 단일 대시보드에 통합
          - CPU/디스크/에러코드 기반 이메일 알림 시스템 구축으로 대응 시간 단축
          - 서비스 로그, DB exporter, Redis exporter 등 다양한 메트릭과 로그를 수집·통합하여 한 대시보드에서 시스템 상태, 성능, 분산 트레이스까지 통합 모니터링 가능하도록 개선
          - 특정 지표(CPU, 디스크 용량, HTTP 500 에러 등) 기반 이메일 알림 시스템을 구축하여 장애 발생 시 신속한 대응이 가능하도록 자동화
          - 통합 모니터링 시스템 도입으로 운영 리소스 절감, 장애 대응 속도 및 서비스 신뢰성 향상
      - layout: left
        title: 데이터베이스 운영 효율화
        description: |
         - 마이그레이션 도구 Flyway 도입, 수동 쿼리 배포 방식 → 자동화된 스키마 관리 체계로 개선
         - Master-Slave 간 replication delay 이슈 분석 및 구조 개선
         - 느린 쿼리 Fetch Time 병목 분석 및 성능 개선 진행
      - layout: left
        title: 기타 DevOps 업무
        description: |
         - 폐쇄망 내 Nexus 프라이빗 이미지 레지스트리 연동 및 배포 자동화 구축
         - 사내 보안 강화를 위해 VPN 서버 구성 및 OPNsense 방화벽 설치 및 정책 설정
         - Jenkins 기반 파이프라인 구성 및 CI/CD 운영 최적화
  - title: Skill
    layout: list
    content:
    - layout: left
      title: Backend
      description: | # this will include new lines to allow paragraphs
        * Java
        * Spring Boot, Spring MVC, Spring Batch
        * JPA, Querydsl
        * Junit4/5, Mockito
        * Gradle
    - layout: left
      title: DevOps
      description: | # this will include new lines to allow paragraphs
        * MySQL, MariaDB
        * Jenkins
        * AWS EKS, S3, EC2, Route53
        * DockerSwarm, K8S
        * Nginx
        * Grafana, Prometheus, Loki, Tempo
        * Ubuntu
  - title: Education
    layout: list
    content:
      - layout: left
        title: 동의대학교
        sub_title: e-비즈니스학과
        caption: 2015.03~2022.02

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
